#!/usr/bin/env bun
/**
 * Cross-platform autostart manager for EchoType (run-from-source).
 *
 * Usage:
 *   bun run autostart:enable   — register EchoType to start at login
 *   bun run autostart:disable  — remove the autostart registration
 *   bun run autostart:status   — check if autostart is registered
 */

import { execSync } from "child_process";
import { existsSync, mkdirSync, writeFileSync, unlinkSync } from "fs";
import { join, resolve } from "path";
import { homedir, platform } from "os";

const PROJECT_DIR = resolve(import.meta.dirname, "..");
const APP_NAME = "EchoType";
const APP_ID = "com.echotype.dev";

// ---------------------------------------------------------------------------
// Windows
// ---------------------------------------------------------------------------

function windowsPaths() {
  const vbs = join(PROJECT_DIR, "scripts", "start-hidden.vbs");
  const startupDir = join(
    process.env.APPDATA || join(homedir(), "AppData", "Roaming"),
    "Microsoft",
    "Windows",
    "Start Menu",
    "Programs",
    "Startup"
  );
  const shortcut = join(startupDir, "EchoType.vbs");
  return { vbs, startupDir, shortcut };
}

function windowsEnable() {
  const { vbs, shortcut } = windowsPaths();

  // Generate VBS launcher that starts bun run dev without a console window
  const vbsContent = `' Auto-generated by EchoType autostart script
Set WshShell = CreateObject("WScript.Shell")
WshShell.CurrentDirectory = "${PROJECT_DIR.replace(/\//g, "\\")}"
WshShell.Run "bash -c ""source .env && bun run tauri dev""", 0, False
`;
  writeFileSync(vbs, vbsContent);
  console.log(`Created launcher: ${vbs}`);

  // Copy into the Windows Startup folder (runs at login, no admin needed)
  writeFileSync(shortcut, vbsContent);
  console.log(`Installed to Startup folder: ${shortcut}`);
  console.log(`\nAutostart enabled. EchoType will start at login.`);
}

function windowsDisable() {
  const { vbs, shortcut } = windowsPaths();

  if (existsSync(shortcut)) {
    unlinkSync(shortcut);
    console.log(`Removed from Startup folder: ${shortcut}`);
  }

  if (existsSync(vbs)) {
    unlinkSync(vbs);
    console.log(`Removed launcher: ${vbs}`);
  }

  console.log("\nAutostart disabled.");
}

function windowsStatus() {
  const { shortcut } = windowsPaths();
  if (existsSync(shortcut)) {
    console.log(`Autostart is ENABLED`);
    console.log(`Startup entry: ${shortcut}`);
  } else {
    console.log("Autostart is DISABLED (no startup entry found)");
  }
}

// ---------------------------------------------------------------------------
// macOS (launchd)
// ---------------------------------------------------------------------------

function macosPaths() {
  const plistDir = join(homedir(), "Library", "LaunchAgents");
  const plist = join(plistDir, `${APP_ID}.plist`);
  return { plistDir, plist };
}

function macosEnable() {
  const { plistDir, plist } = macosPaths();

  if (!existsSync(plistDir)) {
    mkdirSync(plistDir, { recursive: true });
  }

  const plistContent = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${APP_ID}</string>
    <key>WorkingDirectory</key>
    <string>${PROJECT_DIR}</string>
    <key>ProgramArguments</key>
    <array>
        <string>bash</string>
        <string>-c</string>
        <string>source .env &amp;&amp; bun run tauri dev</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>${PROJECT_DIR}/logs/autostart-stdout.log</string>
    <key>StandardErrorPath</key>
    <string>${PROJECT_DIR}/logs/autostart-stderr.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
    </dict>
</dict>
</plist>
`;
  writeFileSync(plist, plistContent);
  console.log(`Created plist: ${plist}`);

  // Ensure logs directory exists
  const logsDir = join(PROJECT_DIR, "logs");
  if (!existsSync(logsDir)) {
    mkdirSync(logsDir, { recursive: true });
  }

  try {
    execSync(`launchctl load "${plist}"`, { stdio: "inherit" });
    console.log(`\nAutostart enabled. EchoType will start at login.`);
  } catch (e: any) {
    console.error("Failed to load launch agent:", e.message);
    process.exit(1);
  }
}

function macosDisable() {
  const { plist } = macosPaths();

  if (existsSync(plist)) {
    try {
      execSync(`launchctl unload "${plist}"`, { stdio: "ignore" });
    } catch {}
    unlinkSync(plist);
    console.log(`Removed plist: ${plist}`);
  }

  console.log("\nAutostart disabled.");
}

function macosStatus() {
  const { plist } = macosPaths();

  if (existsSync(plist)) {
    try {
      const output = execSync(`launchctl list | grep ${APP_ID}`, {
        encoding: "utf-8",
      });
      console.log(`Autostart is ENABLED (loaded)\n`);
      console.log(output.trim());
    } catch {
      console.log(`Autostart is ENABLED (plist exists but not currently loaded)`);
    }
  } else {
    console.log("Autostart is DISABLED (no launch agent found)");
  }
}

// ---------------------------------------------------------------------------
// Linux (systemd user service)
// ---------------------------------------------------------------------------

function linuxPaths() {
  const serviceDir = join(homedir(), ".config", "systemd", "user");
  const service = join(serviceDir, "echotype.service");
  return { serviceDir, service };
}

function linuxEnable() {
  const { serviceDir, service } = linuxPaths();

  if (!existsSync(serviceDir)) {
    mkdirSync(serviceDir, { recursive: true });
  }

  const serviceContent = `# Auto-generated by EchoType autostart script
[Unit]
Description=EchoType Dictation App (dev)
After=graphical-session.target

[Service]
Type=simple
WorkingDirectory=${PROJECT_DIR}
ExecStart=bash -c 'source .env && bun run tauri dev'
Restart=on-failure
RestartSec=5
Environment=DISPLAY=:0

[Install]
WantedBy=default.target
`;
  writeFileSync(service, serviceContent);
  console.log(`Created service: ${service}`);

  try {
    execSync("systemctl --user daemon-reload", { stdio: "inherit" });
    execSync("systemctl --user enable echotype.service", { stdio: "inherit" });
    console.log(`\nAutostart enabled. EchoType will start at login.`);
    console.log("To start now: systemctl --user start echotype.service");
    console.log("View logs:    journalctl --user -u echotype.service -f");
  } catch (e: any) {
    console.error("Failed to enable service:", e.message);
    process.exit(1);
  }
}

function linuxDisable() {
  const { service } = linuxPaths();

  try {
    execSync("systemctl --user stop echotype.service", { stdio: "ignore" });
    execSync("systemctl --user disable echotype.service", { stdio: "ignore" });
  } catch {}

  if (existsSync(service)) {
    unlinkSync(service);
    console.log(`Removed service: ${service}`);
  }

  try {
    execSync("systemctl --user daemon-reload", { stdio: "ignore" });
  } catch {}

  console.log("\nAutostart disabled.");
}

function linuxStatus() {
  try {
    const output = execSync(
      "systemctl --user is-enabled echotype.service 2>/dev/null",
      { encoding: "utf-8" }
    ).trim();
    if (output === "enabled") {
      console.log("Autostart is ENABLED\n");
      execSync("systemctl --user status echotype.service", {
        stdio: "inherit",
      });
    } else {
      console.log(`Autostart is DISABLED (state: ${output})`);
    }
  } catch {
    console.log("Autostart is DISABLED (no service found)");
  }
}

// ---------------------------------------------------------------------------
// Dispatch
// ---------------------------------------------------------------------------

const action = process.argv[2];

if (!action || !["enable", "disable", "status"].includes(action)) {
  console.log(`EchoType Autostart Manager\n`);
  console.log("Usage:");
  console.log("  bun run autostart:enable   Register autostart at login");
  console.log("  bun run autostart:disable  Remove autostart registration");
  console.log("  bun run autostart:status   Check current autostart state");
  process.exit(0);
}

console.log(`Platform: ${platform()}`);
console.log(`Project:  ${PROJECT_DIR}\n`);

const handlers: Record<string, Record<string, () => void>> = {
  win32: { enable: windowsEnable, disable: windowsDisable, status: windowsStatus },
  darwin: { enable: macosEnable, disable: macosDisable, status: macosStatus },
  linux: { enable: linuxEnable, disable: linuxDisable, status: linuxStatus },
};

const platformHandlers = handlers[platform()];
if (!platformHandlers) {
  console.error(`Unsupported platform: ${platform()}`);
  console.error("Supported: Windows, macOS, Linux");
  process.exit(1);
}

platformHandlers[action]();
